#!/usr/bin/env bash
#
# plxy.sh - one entry point for the DrowsyGuard dev loop.
#
#   ./plxy.sh dev            build, flash and open the monitor  <- the usual one
#   ./plxy.sh help           every command
#
# Why this exists rather than calling idf.py directly:
#
#   1. ESP-IDF's export.ps1 derives its virtualenv name from whichever `python`
#      is first on PATH. This project ships a .venv on Python 3.13, so export
#      computes `idf5.5_py3.13_env`, an environment that was never installed,
#      and dies with "ESP-IDF Python virtual environment not found" - which
#      reads like a broken IDF install rather than a PATH-shadowing problem.
#      This script scrubs the project tree off PATH and asks idf_tools.py for
#      the real environment instead of guessing.
#   2. The board exposes two USB interfaces and neither behaves the way the
#      documentation assumes. On the CH343 UART bridge the reset line reaches EN
#      but not GPIO0, so nothing can drive it into download mode and flashing
#      fails with "Wrong boot mode detected (0x28)" - `flash` below detects that
#      and asks for one BOOT press. On the native USB-Serial/JTAG interface the
#      opposite holds: it sits in the ROM loader after every reset, so the
#      monitor shows nothing but "waiting for download". `port` says which one
#      the cable is in.
#   3. The interesting output of this firmware is not on the serial port at all
#      any more - it is a web page. `wifi`, `status` and `open` bridge that gap.
#
# Works in Git Bash on Windows (the environment this project is developed in).

set -o pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FW="$REPO/firmware/esp32s3"

# --------------------------------------------------------------------------- #
# pretty output
# --------------------------------------------------------------------------- #
if [ -t 1 ]; then
    B=$'\033[1m'; DIM=$'\033[2m'; R=$'\033[31m'; G=$'\033[32m'
    Y=$'\033[33m'; C=$'\033[36m'; Z=$'\033[0m'
else
    B=''; DIM=''; R=''; G=''; Y=''; C=''; Z=''
fi
say()  { printf '%s==>%s %s\n' "$C$B" "$Z" "$*"; }
ok()   { printf '%s  ok%s  %s\n' "$G" "$Z" "$*"; }
warn() { printf '%s  !!%s  %s\n' "$Y" "$Z" "$*"; }
die()  { printf '%s  xx%s  %s\n' "$R" "$Z" "$*" >&2; exit 1; }

# --------------------------------------------------------------------------- #
# ESP-IDF, run through PowerShell
# --------------------------------------------------------------------------- #
# ESP-IDF refuses to run under MSYS/MinGW outright - both idf.py and
# idf_tools.py bail with "MSys/Mingw is not supported" the moment they see
# MSYSTEM in the environment - and that guard is right: MSYS rewrites anything
# that looks like a path when it crosses into a native process, which corrupts
# the compiler command lines. So this script keeps the bash front end the
# project asked for and hands the actual build to PowerShell, which is the
# supported environment on Windows.
#
# The helper below is written to a temp file rather than squeezed through
# `powershell -Command`, because quoting a whole prelude through bash into
# PowerShell is its own bug farm. It does four things the plain
# `export.ps1` cannot do here:
#
#   * clears MSYSTEM, which PowerShell inherits from this shell and which would
#     trip the same guard one level down (a false positive - the process really
#     is PowerShell);
#   * rebuilds PATH from the Windows registry instead of inheriting bash's POSIX
#     PATH, which is meaningless to native tools;
#   * drops this repository from PATH, because its .venv is Python 3.13 and
#     export.ps1 derives the IDF virtualenv name from whichever python it finds
#     first - it then looks for idf5.5_py3.13_env, which was never installed,
#     and reports a missing virtualenv rather than a shadowing problem;
#   * picks the IDF-managed interpreter explicitly.

IDF_PS="${TMPDIR:-/tmp}/plxy-idf.ps1"

write_idf_helper() {
    [ -f "$IDF_PS" ] && [ "$IDF_PS" -nt "${BASH_SOURCE[0]}" ] && return 0
    cat >"$IDF_PS" <<'PS1'
# Generated by plxy.sh. Runs one ESP-IDF command in a sane environment.
param([Parameter(ValueFromRemainingArguments = $true)] $Args)
$ErrorActionPreference = 'Continue'

# Inherited from the calling shell; both would abort idf.py.
Remove-Item Env:MSYSTEM      -ErrorAction SilentlyContinue
Remove-Item Env:VIRTUAL_ENV  -ErrorAction SilentlyContinue
Remove-Item Env:PYTHONHOME   -ErrorAction SilentlyContinue
Remove-Item Env:PYTHONPATH   -ErrorAction SilentlyContinue

if (-not $env:IDF_TOOLS_PATH) { $env:IDF_TOOLS_PATH = 'C:\Espressif' }
if (-not $env:IDF_PATH) {
    $found = Get-ChildItem "$env:IDF_TOOLS_PATH\frameworks" -Directory -Filter 'esp-idf-v*' `
             -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
    if (-not $found) { Write-Error 'ESP-IDF not found under $env:IDF_TOOLS_PATH\frameworks'; exit 2 }
    $env:IDF_PATH = $found.FullName
}

$py = Get-ChildItem "$env:IDF_TOOLS_PATH\python_env" -Directory -Filter 'idf*_py*_env' `
      -ErrorAction SilentlyContinue | Sort-Object Name | Select-Object -Last 1
if (-not $py) { Write-Error 'no ESP-IDF python env - re-run the IDF installer'; exit 2 }
$py = Join-Path $py.FullName 'Scripts\python.exe'

# The real Windows PATH, minus this repository (its .venv shadows IDF's python).
$base = @(
  [Environment]::GetEnvironmentVariable('Path', 'Machine'),
  [Environment]::GetEnvironmentVariable('Path', 'User')
) -join ';'
$base = ($base -split ';' | Where-Object { $_ -and $_ -notmatch 'PLXY_DrowsyGuard' }) -join ';'
$env:PATH = $base

# Tool locations come from idf_tools.py rather than being guessed.
$kv = & $py "$env:IDF_PATH\tools\idf_tools.py" export --format key-value 2>$null
if (-not $kv) { Write-Error 'idf_tools.py export produced nothing'; exit 2 }
foreach ($line in $kv) {
    if ($line -match '^([A-Z_0-9]+)=(.*)$') {
        $n = $Matches[1]; $v = $Matches[2]
        if ($n -eq 'PATH') { $env:PATH = $v.Replace('%PATH%', $base) }
        else { Set-Item -Path "env:$n" -Value $v }
    }
}

Set-Location $env:PLXY_FW

# --esptool: run esptool directly instead of idf.py. Needed because esptool's own
# reset sequences cannot reach download mode on this board, so flashing has to be told
# not to try (--before no_reset) once something else has put it there.
if ($Args.Count -gt 0 -and $Args[0] -eq '--esptool') {
    $rest = @($Args[1..($Args.Count - 1)])
    Remove-Item Env:ESPTOOL_CUSTOM_RESET_SEQUENCE -ErrorAction SilentlyContinue
    & $py -m esptool @rest
    exit $LASTEXITCODE
}

# --python: run a project script with ESP-IDF's interpreter, which has pyserial.
# scripts/board_reset.py is the caller - it drives the reset lines directly, which is
# what puts this board in the loader without the BOOT button.
if ($Args.Count -gt 0 -and $Args[0] -eq '--python') {
    $rest = @($Args[1..($Args.Count - 1)])
    & $py @rest
    exit $LASTEXITCODE
}

& $py "$env:IDF_PATH\tools\idf.py" @Args
exit $LASTEXITCODE
PS1
}

# Runs `idf.py <args>` in the firmware directory. Returns idf.py's exit code.
idf() {
    write_idf_helper
    PLXY_FW="$(cygpath -w "$FW")" \
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$IDF_PS")" "$@"
}

# Runs `python -m esptool <args>`, same environment. Set PLXY_DIR to run it
# somewhere other than the firmware directory: `@flash_args` is resolved relative
# to the working directory of the PowerShell child, not of this shell, so a `cd`
# out here would have no effect on it.
esptool() {
    write_idf_helper
    PLXY_FW="$(cygpath -w "${PLXY_DIR:-$FW}")" \
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$IDF_PS")" \
        --esptool "$@"
}

# True when the chip is already sitting in the ROM download loader. --before
# no_reset is the point: the default reset sequence would knock it back out.
in_download_mode() {
    esptool --chip esp32s3 -p "$1" --before no_reset --after no_reset \
        --connect-attempts 2 chip_id >/dev/null 2>&1
}

# Runs a project script with ESP-IDF's Python, which has pyserial. The project venv
# does not, and installing it there would be a second copy for one caller.
idf_python() {
    write_idf_helper
    PLXY_FW="$(cygpath -w "$REPO")" \
        powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$(cygpath -w "$IDF_PS")" \
        --python "$@"
}

# Put the chip in the ROM loader by driving the reset lines directly.
#
# This board's auto-reset lines are INVERTED relative to esptool's convention, which
# is the whole reason esptool cannot do it and why the instructions below used to be
# the only route. scripts/board_reset.py has the measurements. It verifies the ROM
# banner, so a false success is not possible.
enter_download_mode() {
    idf_python "scripts/board_reset.py" "$1" --download --quiet >/dev/null 2>&1
}

# --------------------------------------------------------------------------- #
# serial port
# --------------------------------------------------------------------------- #
# Prefer a USB-UART bridge over the ESP32-S3's native USB-Serial/JTAG: on this
# board only the bridge resets into the application reliably. Bluetooth virtual
# COM ports are excluded outright - they enumerate on most laptops and are never
# the board.
detect_port() {
    [ -n "$PLXY_PORT" ] && { echo "$PLXY_PORT"; return; }
    powershell.exe -NoProfile -Command '
      $devs = Get-CimInstance Win32_PnPEntity |
              Where-Object { $_.Name -match "\(COM\d+\)" -and $_.Name -notmatch "Bluetooth" }
      $rank = { param($n)
        if ($n -match "CH343|CH340|CP210|FTDI|Silicon Labs") { 0 }
        elseif ($n -match "JTAG|USB Serial Device")          { 1 }
        else                                                 { 2 } }
      $best = $devs | Sort-Object { & $rank $_.Name } | Select-Object -First 1
      if ($best -and $best.Name -match "\((COM\d+)\)") { $Matches[1] }
    ' 2>/dev/null | tr -d '\r\n'
}

port_table() {
    powershell.exe -NoProfile -Command '
      Get-CimInstance Win32_PnPEntity |
        Where-Object { $_.Name -match "\(COM\d+\)" } |
        ForEach-Object { $_.Name }
    ' 2>/dev/null | tr -d '\r'
}

require_port() {
    PORT="$(detect_port)"
    [ -n "$PORT" ] || die "no serial port found. Plug the board into the UART USB-C socket, then: ./plxy.sh port"
}

# --------------------------------------------------------------------------- #
# device HTTP API
# --------------------------------------------------------------------------- #
# 192.168.4.1 is fixed: it is the ESP-IDF SoftAP gateway address. Override with
# PLXY_HOST when the board is joined to a network in station mode instead.
HOST="${PLXY_HOST:-192.168.4.1}"

api() {
    local method="$1"; shift
    command -v curl >/dev/null || die "curl not found"
    curl -sS --max-time 5 -X "$method" "http://$HOST$1" || return 1
}

reachable() { curl -sS --max-time 3 -o /dev/null "http://$HOST/api/status" 2>/dev/null; }

wifi_setting() {  # wifi_setting WIFI_AP_PASSWORD
    sed -n "s/^#define $1[[:space:]]*\"\(.*\)\".*/\1/p" "$FW/main/board_wifi.h" | head -1
}

# --------------------------------------------------------------------------- #
# commands
# --------------------------------------------------------------------------- #
cmd_help() {
    cat <<EOF
${B}plxy.sh${Z} - DrowsyGuard dev loop

${B}firmware${Z}
  dev                build, flash and monitor            ${DIM}the usual one${Z}
  build              compile only
  flash              flash without opening the monitor
  monitor            open the serial console              ${DIM}Ctrl+] to exit${Z}
  reconfigure        re-resolve managed components
  menuconfig         ESP-IDF config UI
  size               binary size breakdown
  clean | fullclean  drop build artefacts (fullclean also drops sdkconfig)
  erase              erase the whole flash                ${DIM}wipes NVS + Wi-Fi cal${Z}

${B}device${Z}
  port               list serial ports and say which one will be used
  wifi               how to reach the live preview from a phone
  open               open the preview in your browser
  status             pretty-print GET /api/status
  watch              poll the risk/PERCLOS line once a second
  snapshot [file]    save one JPEG frame                  ${DIM}default: snapshot.jpg${Z}
  alert [reason]     play a warning: drowsy|microsleep|yawn|nod
  mute | unmute      silence or restore the speaker

${B}project${Z}
  test               python test suite
  diagrams           regenerate the tutorial figures and poster
  doctor             check toolchain, port and device

${B}environment${Z}
  PLXY_PORT=COM9     force a serial port
  PLXY_HOST=10.0.0.5 talk to the board over station mode instead of its own AP
EOF
}

cmd_build()       { say "building"; idf build; }
cmd_reconfigure() { say "resolving components"; idf reconfigure; }
cmd_menuconfig()  { idf menuconfig; }
cmd_size()        { idf size; }
cmd_clean()       { say "clean"; idf clean; }

cmd_fullclean() {
    say "fullclean (build/ and sdkconfig)"
    idf fullclean
    rm -f "$FW/sdkconfig"
    ok "sdkconfig removed - the next build re-seeds it from sdkconfig.defaults"
}

# Flashing on this board is not the one-liner it is on most: its USB-UART bridge
# drives EN but not GPIO0, so no reset sequence can reach download mode and
# `idf.py flash` fails with "Wrong boot mode detected (0x28)". The chip has to be
# put in the loader by hand once, and then flashed with the reset lines left
# alone. So: check for the loader first, and only fall back to a normal flash.
#
# esptool directly rather than `idf.py flash`, for one reason: when the port it
# is given fails, idf.py walks every other COM port on the machine and buries the
# real error under a page of Bluetooth timeouts. Here `-p` means `-p`.
#
# $1 is esptool's --before: `no_reset` when the chip is already in the loader
# (touching the lines would knock it back out), `default_reset` otherwise.
flash_binaries() {
    [ -s "$FW/build/flash_args" ] || die "no build to flash - run ./plxy.sh build first"
    PLXY_DIR="$FW/build" esptool --chip esp32s3 -p "$PORT" -b 460800 \
        --before "$1" --after hard_reset write_flash "@flash_args"
}

cmd_flash() {
    require_port
    cmd_build || die "build failed"

    say "checking $PORT"
    if in_download_mode "$PORT"; then
        ok "already in the ROM loader - flashing without touching the reset lines"
        flash_binaries no_reset || die "flash failed"
    elif enter_download_mode "$PORT" && in_download_mode "$PORT"; then
        # The lines are inverted on this board, so the sequence esptool will not try
        # is the one that works. No BOOT press needed.
        ok "put it in the ROM loader over the serial lines - no BOOT press needed"
        flash_binaries no_reset || die "flash failed"
    else
        say "flashing $PORT"
        # esptool walks every other serial port when the one it was given fails,
        # which on a laptop means a screenful of Bluetooth timeouts between the
        # real error and the reader. Drop that chatter; keep everything else.
        flash_binaries default_reset 2>&1 | grep -vE \
            '^Serial port COM|failed to connect: (Could not open|Write timeout)|^Failed to get PID|^No serial ports found|^\(could not open port'
        if [ "${PIPESTATUS[0]}" -ne 0 ]; then
            echo
            warn "the board would not enter download mode, even over the raw lines"
            cat <<EOF

  esptool cannot do this on its own here, and ${B}scripts/board_reset.py${Z} - which
  drives the lines directly, with the inverted polarity this board actually uses -
  did not manage it either. Something is different about the connection this time.
  Put it in the loader by hand:

      1. ${B}Hold BOOT down${Z}   (may be labelled IO0)
      2. ${B}Tap RESET${Z}        (or unplug and replug USB) while still holding BOOT
      3. ${B}Release BOOT${Z}

  The board then waits in the loader indefinitely - there is no timing window to
  hit. Re-run ${B}./plxy.sh flash${Z} and it will detect the loader and go straight in.
EOF
            return 1
        fi
    fi
    ok "flashed"
    cmd_wifi
}

cmd_monitor() {
    require_port
    say "monitor on $PORT  ${DIM}(Ctrl+] to exit)${Z}"
    idf -p "$PORT" monitor
}

cmd_dev() {
    cmd_flash || return 1
    cmd_monitor
}

cmd_erase() {
    require_port
    warn "this erases NVS too, including the Wi-Fi calibration data"
    read -r -p "  erase all flash on $PORT? [y/N] " a
    case "$a" in [yY]*) idf -p "$PORT" erase-flash ;; *) echo "  skipped" ;; esac
}

cmd_port() {
    say "serial ports"
    local list; list="$(port_table)"
    [ -n "$list" ] || { warn "none found - is the cable a data cable, and in the UART socket?"; return 1; }
    echo "$list" | sed 's/^/     /'
    local p; p="$(detect_port)"
    echo
    if [ -n "$p" ]; then
        ok "will use $p"
        case "$(echo "$list" | grep "($p)")" in
            *CH343*|*CH340*|*CP210*|*FTDI*)
                echo "     ${DIM}USB-UART bridge - resets into the app reliably on this board${Z}" ;;
            *JTAG*|*"USB Serial Device"*)
                warn "this is the native USB-Serial/JTAG interface"
                echo "     ${DIM}On this board it re-enters the ROM download loader after every${Z}"
                echo "     ${DIM}reset, so the monitor may show only 'waiting for download'.${Z}"
                echo "     ${DIM}Move the cable to the other USB-C socket (the UART one).${Z}" ;;
        esac
    else
        warn "no candidate port"
    fi
}

cmd_wifi() {
    local ssid pw
    ssid="$(sed -n 's/^#define WIFI_AP_SSID_PREFIX[[:space:]]*"\(.*\)".*/\1/p' \
            "$FW/main/board_wifi.h" | head -1)"
    pw="$(wifi_setting WIFI_AP_PASSWORD)"
    cat <<EOF

${B}Watch the camera from your phone${Z}

  1. Power the board. You should hear ${B}three rising notes${Z}.
  2. On your phone: Settings > Wi-Fi, join

         network   ${B}${ssid}-XXXXXX${Z}   ${DIM}(XXXXXX = last 3 bytes of the board's MAC)${Z}
         password  ${B}${pw:-<open network>}${Z}

     Your phone will warn that the network has no internet. That is correct -
     the board ${B}is${Z} the network.
  3. Open ${B}http://${HOST}/${Z} in any browser.

  ${DIM}The exact SSID is printed in the boot log:  wifi: SoftAP "..." up on channel 6${Z}
  ${DIM}One live viewer at a time; a second phone gets still frames instead.${Z}
EOF
}

cmd_open() {
    say "opening http://$HOST/"
    reachable || warn "no answer from $HOST - are you joined to the board's Wi-Fi?"
    powershell.exe -NoProfile -Command "Start-Process 'http://$HOST/'" >/dev/null 2>&1 \
        || echo "  open http://$HOST/ manually"
}

cmd_status() {
    local j; j="$(api GET /api/status)" || die "no answer from $HOST - join the board's Wi-Fi first (./plxy.sh wifi)"
    if command -v python >/dev/null; then
        echo "$j" | python -c 'import json,sys; print(json.dumps(json.load(sys.stdin), indent=2))'
    else
        echo "$j"
    fi
}

cmd_watch() {
    command -v python >/dev/null || die "python not found"
    say "polling http://$HOST/api/status  ${DIM}(Ctrl+C to stop)${Z}"
    while true; do
        local j; j="$(api GET /api/status 2>/dev/null)"
        if [ -z "$j" ]; then
            printf '\r%s  waiting for the board...%s' "$Y" "$Z"
        else
            echo "$j" | python -c '
import json, sys
s = json.load(sys.stdin)
f, r, e = s["face"], s["risk"], s["eyes"]
print(f"fps {s[\"fps\"]:5.1f}  risk {r[\"score\"]:.2f}/{r[\"trigger\"]:.2f}"
      f"  perclos {e[\"perclos\"]:.2f}  eye {e[\"closed\"]:.2f}"
      f"  face {\"yes\" if f[\"found\"] else \" no\"}"
      f"  alerts {s[\"alert\"][\"count\"]}"
      f"  viewers {s[\"stream\"][\"viewers\"]}"
      f"  heap {s[\"mem\"][\"heap\"]//1024}k")'
        fi
        sleep 1
    done
}

cmd_snapshot() {
    local out="${1:-snapshot.jpg}"
    command -v curl >/dev/null || die "curl not found"
    curl -sS --max-time 10 -o "$out" "http://$HOST/api/snapshot" \
        || die "no answer from $HOST"
    [ -s "$out" ] || die "empty response - is the camera up? ./plxy.sh status"
    ok "wrote $out ($(wc -c <"$out" | tr -d ' ') bytes)"
}

cmd_alert() {
    local reason
    case "${1:-drowsy}" in
        drowsy|"")   reason=0 ;;
        microsleep)  reason=1 ;;
        yawn|yawning) reason=2 ;;
        nod|head_nod|headnod) reason=3 ;;
        *) die "reason must be one of: drowsy microsleep yawn nod" ;;
    esac
    api POST "/api/alert-test?reason=$reason" && echo
}

cmd_mute()   { api POST "/api/settings?muted=1" && echo; }
cmd_unmute() { api POST "/api/settings?muted=0" && echo; }

cmd_test() {
    local py="$REPO/.venv/Scripts/python.exe"
    [ -x "$py" ] || py=python
    say "pytest"
    ( cd "$REPO" && "$py" -m pytest tests/ -q )
}

cmd_diagrams() {
    local py="$REPO/.venv/Scripts/python.exe"
    [ -x "$py" ] || py=python
    say "regenerating figures"
    ( cd "$REPO" \
      && "$py" scripts/generate_tutorial_diagrams.py \
      && "$py" scripts/generate_step_diagrams.py \
      && "$py" scripts/generate_wiring_poster.py )
}

cmd_doctor() {
    say "toolchain"
    local ver
    ver="$(idf --version 2>&1 | tr -d '\r' | grep -oE 'v[0-9]+\.[0-9]+[^ ]*' | head -1)"
    if [ -n "$ver" ]; then
        ok "ESP-IDF  $ver"
    else
        warn "idf.py did not answer - run ./plxy.sh build to see why"
    fi

    echo; say "board"
    cmd_port || true
    local bin="$FW/build/drowsyguard_esp32s3.bin"
    echo
    if [ -f "$bin" ]; then
        ok "built    $(wc -c <"$bin" | tr -d ' ') bytes, $(date -r "$bin" '+%Y-%m-%d %H:%M')"
    else
        warn "no build yet - run ./plxy.sh build"
    fi

    echo; say "device"
    if reachable; then
        ok "reachable at http://$HOST/"
        cmd_status | grep -E '"(fps|camera|models|eye_model|ssid|ip)"' | sed 's/^/     /'
    else
        warn "not reachable at $HOST"
        echo "     ${DIM}Expected unless you are joined to the board's Wi-Fi: ./plxy.sh wifi${Z}"
    fi
}

# --------------------------------------------------------------------------- #
case "${1:-help}" in
    dev)          shift; cmd_dev "$@" ;;
    build)        shift; cmd_build "$@" ;;
    flash)        shift; cmd_flash "$@" ;;
    monitor|mon)  shift; cmd_monitor "$@" ;;
    reconfigure)  shift; cmd_reconfigure "$@" ;;
    menuconfig)   shift; cmd_menuconfig "$@" ;;
    size)         shift; cmd_size "$@" ;;
    clean)        shift; cmd_clean "$@" ;;
    fullclean)    shift; cmd_fullclean "$@" ;;
    erase)        shift; cmd_erase "$@" ;;
    port|ports)   shift; cmd_port "$@" ;;
    wifi)         shift; cmd_wifi "$@" ;;
    open)         shift; cmd_open "$@" ;;
    status)       shift; cmd_status "$@" ;;
    watch)        shift; cmd_watch "$@" ;;
    snapshot|snap) shift; cmd_snapshot "$@" ;;
    alert)        shift; cmd_alert "$@" ;;
    mute)         shift; cmd_mute "$@" ;;
    unmute)       shift; cmd_unmute "$@" ;;
    test)         shift; cmd_test "$@" ;;
    diagrams)     shift; cmd_diagrams "$@" ;;
    doctor)       shift; cmd_doctor "$@" ;;
    help|-h|--help) cmd_help ;;
    *) die "unknown command '$1' - try ./plxy.sh help" ;;
esac
