#!/usr/bin/env python3
"""Turn open_closed_eye.onnx into a C header the firmware links directly.

Why not ESP-DL and a quantized .espdl, which is what the rest of the vision stack
uses? Because that route is blocked and this one is not:

  * ESP-DL loads `.espdl`, produced by **esp-ppq**, which is not on PyPI at all -
    `pip install esp-ppq` fails outright, so the advice in the old
    scripts/quantize_espdl.py stub was simply wrong.
  * Quantization also needs a calibration set of real eye crops. This repository
    has none: the DDD corpus was deleted after import.

Neither of those is worth solving for this particular network. It is four
convolutions and 11,250 parameters - 45 kB as float32, which the ESP32-S3 has in
flash to spare - so the firmware runs it directly in float and skips quantization
entirely. That also removes quantization error from the accuracy question, which
matters here because the model is already weak on visible light (see gap 6 in
PROJECT_STATE.md).

The graph, for the C implementation to mirror exactly:

    input 1x3x32x32
    Conv  conv1  3->10  3x3 valid        -> 10x30x30
    MaxPool 2x2 s2                       -> 10x15x15
    Relu
    Conv  conv2  10->20 3x3 valid        -> 20x13x13
    MaxPool 2x2 s2                       -> 20x6x6     (13//2, ceil_mode=0)
    Relu
    Conv  conv3  20->50 3x3 valid        -> 50x4x4
    Conv  conv4  50->2  1x1, NO BIAS     -> 2x4x4      (and no Relu before it)
    MaxPool 4x4 s4                       -> 2x1x1
    Exp / ReduceSum / Div                -> softmax over the 2 channels

Run:  python scripts/export_eye_model.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ONNX = ROOT / 'models/detectors/open_closed_eye.onnx'
OUT = ROOT / 'firmware/esp32s3/main/eye_model_weights.h'

# The order the C code expects them in.
TENSORS = ['conv1.weight', 'conv1.bias', 'conv2.weight', 'conv2.bias',
           'conv3.weight', 'conv3.bias', 'conv4.weight']


def c_name(onnx_name: str) -> str:
    return 'kEye_' + onnx_name.replace('.', '_')


def emit(name: str, arr) -> str:
    flat = arr.reshape(-1)
    lines = [f'// {name}  shape {tuple(arr.shape)}',
             f'static const float {c_name(name)}[{flat.size}] = {{']
    for i in range(0, flat.size, 8):
        chunk = ', '.join(f'{v:+.8e}f' for v in flat[i:i + 8])
        lines.append(f'    {chunk},')
    lines.append('};')
    return '\n'.join(lines)


def main() -> int:
    try:
        import onnx
        from onnx import numpy_helper
    except ImportError:
        print('needs onnx: pip install onnx', file=sys.stderr)
        return 1

    if not ONNX.is_file():
        print(f'missing {ONNX}\n'
              'fetch it with: python -c "from drowsyguard.eyestate import '
              'fetch_eye_model; fetch_eye_model()"', file=sys.stderr)
        return 1

    model = onnx.load(str(ONNX))
    by_name = {i.name: numpy_helper.to_array(i) for i in model.graph.initializer}
    missing = [t for t in TENSORS if t not in by_name]
    if missing:
        print(f'the graph does not contain {missing}; it is not the model this '
              f'exporter was written for', file=sys.stderr)
        return 1

    total = sum(by_name[t].size for t in TENSORS)
    parts = ['#pragma once',
             '// GENERATED by scripts/export_eye_model.py - do not edit.',
             f'// Source: models/detectors/{ONNX.name}',
             '// open-closed-eye-0001, OpenVINO Model Zoo (Intel), Apache-2.0.',
             f'// {total} parameters, float32.',
             '',
             '// Shapes, so the forward pass can assert against them.',
             '#define EYE_IN_C 3',
             '#define EYE_IN_HW 32',
             '#define EYE_C1 10',
             '#define EYE_C2 20',
             '#define EYE_C3 50',
             '#define EYE_OUT 2',
             '']
    for t in TENSORS:
        parts.append(emit(t, by_name[t]))
        parts.append('')

    OUT.write_text('\n'.join(parts), encoding='utf-8', newline='\n')
    kb = OUT.stat().st_size / 1024
    print(f'wrote {OUT.relative_to(ROOT)}  ({total} params, {kb:.0f} kB of source)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
